# Generated by Django 2.1 on 2018-10-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAccount',
        ),
    ]
