# Generated by Django 2.1 on 2018-09-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_order_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress',
            new_name='address',
        ),
    ]
